### ISSUE TITLE
AWS Access Denied

### ISSUE THREAD

**Issue by mingbackmountain** [serverless-nextjs/serverless-next.js#1043]
Hi guys, I'm trying to deploy my nextjs application using serverless. However, I have encounter this error and I can not find any relevant solution. Can you please help me?

<img width="971" alt="Screen Shot 2564-05-07 at 18 30 28" src="https://user-images.githubusercontent.com/25886138/117443560-80f30c80-af62-11eb-95c7-95bbf1d79844.png">

Here is my serverless.yml

<img width="634" alt="Screen Shot 2564-05-07 at 18 33 15" src="https://user-images.githubusercontent.com/25886138/117443701-b861b900-af62-11eb-80ef-e621f7af5d26.png">

**Comment by dreamchests** [comment]
Hey there,

seems you are missing your AWS credentials to deploy via serverless. Check the [Getting Started](https://github.com/serverless-nextjs/serverless-next.js#getting-started) section, that should resolve it.

If you did, check if they are in the right place. When in doubt and just testing, you can set them inline when calling serverless, i.e.:

```
AWS_ACCESS_KEY_ID=accesskey AWS_SECRET_ACCESS_KEY=sshhh serverless

```

If that is not the issue, you should check if the user behind those credentials has the correct access rights to all the resources listed in the [AWS permissions](https://github.com/serverless-nextjs/serverless-next.js#aws-permissions) section.

Hope this helps! 

Cheers

**Comment by dphang** [comment]
Yes, please make sure you are setting access keys correctly in the env variables and ensure your deployment user also has all the necessary permissions. From your screenshot it looks like there is some problem accessing S3 bucket.

(Also, one suggestion is to paste the logs instead of using screenshots, as it is more accessible and searchable)

I am closing as assuming it is not issue with this component, but if you find a bug, feel free to open another issue.
