### ISSUE TITLE
Invocations threshold quickly met running on AWS Lambda

### ISSUE THREAD

**Issue by sbilling** [serverless-nextjs/serverless-next.js#1202]
### Describe the bug
We are running a serverless nextjs app on AWS Lambda and are running into some rather serious performance issues when less <5 users are simultaneously using our application. 

### Actual behavior
Each time the nextjs app calls its own internal route, an invocation starts and ends on the lambda. With a default upper threshold of just 1000 invocations we are _quickly_ running into the ceiling and the lambda is starting to drop requests as it is overwhelmed and unresponsive. 

### Expected behavior
It seems ridiculous that such a small crop of users hitting internal API routes would trigger this many concurrent invocations? Is this the expected behavior? What am I missing? 

### Steps to reproduce
Deploy a next serverless app to AWS Lambda that makes 10-20 internal api route calls on page load. All it will take is a handful of refreshes before your lambda explodes. 

### Versions

- OS/Environment:
- @sls-next/serverless-component version: 1.18.0
- Next.js version: "v10.0.0"

### Checklist

- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by raffij** [comment]
Are these all ssr pages making between 10-20 next API calls in `GetServerSideProps`?

**Comment by sbilling** [comment]
@raffij no - we don't make use of any of the SSR features.

**Comment by dphang** [comment]
What are your APIs doing? I don't think I have faced it even though I also make a few simultaneous calls after a page load (to a regular Lambda though). Hopefully the APIs are not keeping the Lambda containers open somehow (I think doing some async work that is not terminated properly within the request might cause issues, or a Lambda container is waiting on a shared resource like SQL database).

For example I had problems when a regular Lambda was hitting a shared RDS Postgres instance, but that was because Lambda does not do connection pooling and so it was waiting for a free connection (and quickly cause some perf issues).

The best way to debug I think is to add console log statements in your APIs, perform load test and try to check logs.

The latest API handler is pretty simple, so not sure if there are any issues there, it is just requiring the API page and awaiting on the response: https://github.com/serverless-nextjs/serverless-next.js/blob/135e00665162c5f393cedc839ec107fead7be519/packages/libs/lambda-at-edge/src/api-handler.ts#L16-L45

**Comment by jaredgalanis** [comment]
@dphang these api routes are acting primarily as proxies to other external APIs. 

I also think it's possible invocation limits weren't actually being exceeded (it's hard to tell with the precision of standard CloudWatch tooling). The durations do get very long though.

Will try some profiling in the api routes themselves as you suggest.

**Comment by jaredgalanis** [comment]
@dphang I see that there is documentation which indicates that the path to your custom handler is what is needed in the serverless.yml file, but I'm unclear on how to call the default-handler.

I also see there is an old example of how to enable x ray in a custom handler in [this comment](https://github.com/serverless-nextjs/serverless-next.js/issues/12#issuecomment-487752306). Not sure if this would still work.

**Comment by dphang** [comment]
Sorry for the late response... I think X-ray won't work for now as it's an AWS limitation with edge lambdas. As for the original issue, I'm still unsure what could be going on, but will leave it open if anyone has ideas or if you can try to create a repro..

**Comment by jaredgalanis** [comment]
@dphang thanks for replying here. Yeah I noticed that about edge lambdas too. I think the original issue was entirely unrelated to the distro of lambdas so I'll delete this. I think it was external requests that were taking a long time. Appreciate all your guidance.

**Comment by dphang** [comment]
Great that you resolved the issue! Will close it now.
