### ISSUE TITLE
Best way to deploy one API function as a normal lambda due to the limitation of @edge's short timeout

### ISSUE THREAD

**Issue by omarryhan** [serverless-nextjs/serverless-next.js#1318]
I've been working on an app that uses serverless-next-js for a good while now. One of my API functions runs for atleast 3 mins when called. Normal AWS lambdas can stay online for as long as 15 minutes. However, @edge, which is the only kind of Lambda supported by this project can only last up to 30 seconds. I read in other issues that supporting normal lambdas (as well as other function providers) is still in the works. So, sorry if I sound repetitive.

Is there a way I can somehow make a single api page run on normal Lambda (even if it's a hacky way). My other alternative would be to use a different hosting method. e.g. Lightsail or EC2 which have their own set of downsides e.g. manual deployment etc.

Thanks

**Comment by tyler-ground** [comment]
I'd highly recommend separating out your APIs that don't require running on the edge into their own project.  You can still use regular lambda with a separate project.

**Comment by jvarho** [comment]
I'm working on non-edge lambda implementation. (No promises on delivery times.)

However, even there you have a 30s timeout limit due to api gateway limits. The only way to have a longer timeout for a lambda api is to make it async, which means you don't get a response (or only get a 2xx before it even starts executing).

If you can live with async, I would recommend deploying a separate lambda and calling it from the api lambda (@edge) asynchronously. It likely won't be straightforward to integrate async apis and next.js even in the implementation I'm working on.

**Comment by dphang** [comment]
Yeah, I also thought for both APIGW and CloudFront there is a 30 second limit. Not sure it makes sense to try to support it (if even possible) as usually Next.js app use cases are for synchronous APIs where you want fast response, since users are waiting.

If you want long running tasks, it should probably be offloaded to a worker instead of waited on in an API? I guess you can deploy the long-running Lambda separately (via serverless framework, etc.) and then invoke it asynchronously in the Lambda@Edge Next.js API (via https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html, which uses an internal queue).

**Comment by omarryhan** [comment]
Didn't realize that API Gateway also has this hard limit of 30 secs. Splitting the code is not an option for me. One requirement I have is to have all the code must stay in one app. Given that requirement, I decided to move to Elastic Beanstalk (which uses EC2 under the hood == no timeout limits) until a better solution comes up. Also, I'm too lazy to configure workers and write more logic to track the worker's status + fetch the results.

Now that I'm not using this lib anymore, are there instructions on how to delete/uninstall all the services spawned by this lib? Or do I have to go through it manually?

Thanks for your help everyone, much appreciated!

**Comment by dphang** [comment]
The remove command should take care of some resource, but because of Lambda@Edge replication you need to remove it manually

**Comment by omarryhan** [comment]
Thanks a lot @dphang

**Comment by coltenkrauter** [comment]
> I'm working on non-edge lambda implementation. (No promises on delivery times.)
> 

@jvarho, any updates on this?

**Comment by jvarho** [comment]
@coltenkrauter

Hi, life intervened. Currently all my serverless-next-using projects are in maintenance mode, and I'm not working on it at the moment.

However, others have continued work towards a lambda implementation. (See the warnings.)
https://github.com/serverless-nextjs/serverless-next.js/tree/master/packages/libs/lambda

**Comment by coltenkrauter** [comment]
@jvarho, I understand, thanks for letting me know. I totally know how life can happen.

Regardless, you've made some great stuff here. Much appreciated. 👍

**Comment by dphang** [comment]
@coltenkrauter yes as mentioned above I did add an initial “preview” version of lambda which can be deployed with CDK-Terraform right now. However note that it’s not fully tested nor is the DX ready so you’d have to do some DIY to get it fully working (eg if you wanted to use it with plain CDK). Unfortunately had also gotten busier this year so I haven’t actively worked as much on to complete it yet… hopefully in the coming weeks?
