### ISSUE TITLE
Ignore files during upload

### ISSUE THREAD

**Issue by skozer** [serverless-nextjs/serverless-next.js#1399]
**Is your feature request related to a problem? Please describe.**

Some undesired files are being uploaded to S3:

- Source maps in the `_next/static` directory (note: still need to generate them for Sentry)
- System files like `.DS_Store` in the `public` directory

**Describe the solution you'd like**

Is it possible to use something like a `.slsignore` file to specify file patterns to ignore?

**Describe alternatives you've considered**

Similar problem in https://github.com/serverless-nextjs/serverless-next.js/issues/905, but the solution is a bit clunky.

**Comment by dphang** [comment]
Not yet, but that would be a good enhancement.

If you would like to take it up: you can update `readDirectoryFiles` to accept a list of ignore patterns and pass it to `fast-glob` around here: https://github.com/serverless-nextjs/serverless-next.js/blob/878add9fbfd4a207f3648233e5c757a800e154c3/packages/libs/s3-static-assets/src/index.ts#L65-L68

Instead of a `.slsignore` file it might be good to keep it in the `serverless.yml` file?

**Comment by dphang** [comment]
This is done in https://github.com/serverless-nextjs/serverless-next.js/pull/1485 with a new input `build.assetIgnorePatterns`

**Comment by skozer** [comment]
This is great, thanks @dphang!
