### ISSUE TITLE
Next/Script and other NextJS v11 features

### ISSUE THREAD

**Issue by cweekly** [serverless-nextjs/serverless-next.js#1430]
The README mentions "Next 10/11", but it's not clear which features from v11 are supported.
I'm particularly interested in `next/script` (https://nextjs.org/docs/basic-features/script).
If it's supported, this is a friendly suggestion to update the README to clarify; if not, this is a feature request to put `next/script` (and `next/image`, etc) on the roadmap. 
Thanks!

**Comment by jonahallibone** [comment]
@cweekly I don't want to speak for the maintainers, but I can tell you that the `next/image` component is supported. I haven't tried the `next/script` component, but because it doesn't really do anything more than render  a `<script />` tag in the correct place, I don't see how `serverless-next.js` would possible not support it. I've been using `next@11.x` since the day it was released with this component and i've yet to run into a support issue. What I am getting at here, is that unless the `next@11` build isn't compatible (which it is), framework features like `next/script` should work fine

**Comment by cweekly** [comment]
Thanks @jonahallibone, that makes perfect sense. Nice to hear you've been on 11.x since its release. Agreed next/script is likely supported; I'll update here when I get a chance to confirm. Slainte!

**Comment by dphang** [comment]
Yes, you can check the features list to see which are explicitly supported (or planned). The reason is because we need to emulate the server-side features.

If not, it may be supported - for example if it’s purely client side feature, then we don’t need to do anything and get it for free. Script tag should be supported in this case.
