### ISSUE TITLE
ISR regenerates blank pages

### ISSUE THREAD

**Issue by manuelgonzalezrodriguez** [serverless-nextjs/serverless-next.js#1678]
### Issue Summary
In our project we have some pages with ISR. During building phase that pages are generated correctly but when build is deployed and some visit triggers ISR regeneration, those pages are generated as blank pages (html files with 0 bytes).

### Actual behavior
ISR regeneration creates blank pages.

### Expected behavior
Regenerating a page should creates a non-empty html file. 

### Steps to reproduce

- Set some page as ISR mode (add `revalidate` field with some value).
- Build + deploy project.
- Visit a page until trigger ISR regeneration. Next visit will returns a blank page.

### Screenshots/Code/Configuration/Logs
Due to this is a private project we can't share source code. Logs don't show any error or suspect messages.

![Clipboard - 13 de septiembre de 2021 9_31](https://user-images.githubusercontent.com/89073683/133048786-9eac82ad-e35c-41ff-bec2-ab02b165015b.png)
S3 screenshoot with regenerated blank pages (size 0B).

![metadata_good](https://user-images.githubusercontent.com/89073683/133049592-a052e812-0a02-4412-9e9b-fe4bdc93189d.png)
Metadata of a html generated during deploy.

![metadata_bad](https://user-images.githubusercontent.com/89073683/133057167-6a52c8b9-1da3-4e41-8704-3d4fc474ad53.png)
Metadata of a regenerated empty html.

### Versions
- OS/Environment: AWS
- @sls-next/serverless-component version: 3.3.0
- Next.js version: 11.1.0

### Checklist
- [X] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [X] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [X] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Are the corresponding JSON data files generated correctly and it's just HTML being blank? Hm, thought I fixed these issues, but earlier it was because Next.js started not returning html strings from their render function starting in Next.js 11+. So it was throwing an error when trying to store the regenerated page to S3, as the body was not a string.

But if you are not having an error then I suspect it's hitting this line: https://github.com/serverless-nextjs/serverless-next.js/blob/d3a10b2d7ed9d14afd1a09436f9fbf911fde001e/packages/libs/core/src/utils/renderUtils.ts#L38. If so, somehow  `htmlResult` is falsy and so we just save blank HTML but don't log anything. We could probably just use the fallback which should work in all cases

**Comment by dphang** [comment]
Possibly fixed by https://github.com/serverless-nextjs/serverless-next.js/pull/1680. Please give a try and let me know if it works?

**Comment by danicano10** [comment]
Hello @dphang, I am a partner of  @manuelgonzalezrodriguez,

we have tested with the new version and we have the same error, but I see that the lambda is executed correctly and says that the page has been regenerated correctly, but it is not like this 

![Captura de pantalla 2021-09-14 a las 14 22 55](https://user-images.githubusercontent.com/48921003/133297118-7ac6bd3a-645c-4607-8666-6744c6301310.png)


Here we see that the page was created empty

![Captura de pantalla 2021-09-14 a las 14 29 28](https://user-images.githubusercontent.com/48921003/133297396-4b6d7551-78c8-44ed-a5d9-29271f80fb8b.png)

I attach the code of our serverless file in case it helps you

`name: aaaaaaaa
${SHOP_SLUG}:
  component: '@sls-next/serverless-component@v3.4.0-alpha.6'
  inputs:
    memory: 2048
    timeout:
      defaultLambda: 20
      apiLambda: 20
      imageLambda: 20
      regenerationLambda: 20
    name:
      apiLambda: ${SHOP_SLUG}-api
      defaultLambda: ${SHOP_SLUG}-isr
      imageLambda: ${SHOP_SLUG}-images
      regenerationLambda: ${SHOP_SLUG}-regeneration
    description: ${SHOP_NAME} ISR mode
    useServerlessTraceTarget: true
    bucketRegion: eu-west-1
    bucketName: ${SHOP_SLUG}
    cloudfront:
      distributionId: ${CLOUDFRONT_ID}
    build:
      cmd: yarn
      enabled: true
      postBuildCommands:
        - cp -r .serverless_nextjs/default-lambda/chunks .serverless_nextjs/regeneration-lambda/ || true
        - cp -r .serverless_nextjs/default-lambda/node_modules .serverless_nextjs/regeneration-lambda/ || true
        - cp -n .serverless_nextjs/default-lambda/*.js .serverless_nextjs/regeneration-lambda/ || true
        - yarn fixRoutes .serverless_nextjs/default-lambda/manifest.json`

**Comment by dphang** [comment]
Hm, I'm not quite sure then, the `serverless.yml` file looks fine to me. Next.js changed how they render the HTML in later versions, but I thought the fallback should handle those cases. And our e2e tests are testing with 10.2.3 and the latest (11.1+) and have been passing. So I feel your case is something else. Here are some things to try:

1. Are the JSON data files generated correctly?
2. Are any of the logs I added showing up? Here: https://github.com/serverless-nextjs/serverless-next.js/blob/801c391eaaf2a7635676dedbd82525c6a584db57/packages/libs/core/src/utils/renderUtils.ts#L44-L52
3. Can you try other Next.js versions so see if it works? For example, 10.2.3 the page's renderReqToHtml function with render mode renders html as a string. Just want to see if that helps.
4. If not, I would recommend you please try to build from source and add logging statements around there. Possibly after lines 47 & 54 here as this is the fallback function: https://github.com/serverless-nextjs/serverless-next.js/blob/801c391eaaf2a7635676dedbd82525c6a584db57/packages/libs/core/src/utils/renderUtils.ts#L54, https://github.com/serverless-nextjs/serverless-next.js/blob/801c391eaaf2a7635676dedbd82525c6a584db57/packages/libs/core/src/utils/renderUtils.ts#L47
5. Alternatively to (4), if you do not want to build from source and try to debug yourself, please create a minimal reproduction of the bug (i.e create a new repo and try to reproduce the same bug in your private repo) and I can debug further. Unfortunately I can't really help otherwise as I don't know what other dependencies, etc. you have in your code.

**Comment by danicano10** [comment]
Perfect, the team will start with the tests, on the other hand, where the JSON data files are generated?

**Comment by dphang** [comment]
Data files are in S3 in `_next/data/<build_id>/`. They should also be regenerated

**Comment by danicano10** [comment]
Oh perfect, the JSON data file  have been regenerated with content

![Captura de pantalla 2021-09-14 a las 19 26 56](https://user-images.githubusercontent.com/48921003/133305297-1ed672af-989d-4cfa-80a1-828ed2739477.png)

**Comment by manuelgonzalezrodriguez** [comment]
Hello @dphang, thanks for your help, 

1. Reforcing what my coworker said about JSON files, I confirm we have same problem with alpha-6.

This page was regenerated empty, but its JSON has content.
<img width="1243" alt="Captura de pantalla 2021-09-15 a las 8 28 14" src="https://user-images.githubusercontent.com/89073683/133390877-b2b30eb8-c51e-4fca-a831-506441c453cb.png">
HTML file ⬆

<img width="1253" alt="Captura de pantalla 2021-09-15 a las 8 28 35" src="https://user-images.githubusercontent.com/89073683/133391002-c1c68ad2-ca76-4788-b871-e5c3dae5cc27.png">
JSON file ⬆

2. We've found those logs when this blank page was regenerated (2-3 times):
<img width="881" alt="Captura de pantalla 2021-09-15 a las 8 47 20" src="https://user-images.githubusercontent.com/89073683/133393172-6b51e226-845f-4252-bde4-a9702b9991d3.png">

3. Due to project requirements we able not downgrade to 10.2.3 . We can make a minimal sample project to reproduce this error and do this test. But before, we would like to know if this logs (2) are helpful for you.
4. See (3)
5. See (3)

**Comment by dphang** [comment]
Ya, it seems like even after using the fallback. However, can you try Next.js 11.1.2 as well? Hm, it seems that the fallback was not working as expected... https://github.com/serverless-nextjs/serverless-next.js/blob/801c391eaaf2a7635676dedbd82525c6a584db57/packages/libs/core/src/utils/renderUtils.ts#L38, calling `(await page.renderReqToHTML(req, res)) as unknown as string` seems to return empty string twice. Not sure why as this is directly from the page itself (this is from Next.js page code, not our component, it should return a string). Maybe it is buggy on 11.1 though, as the Next.js code changed how they render HTML throughout different minor versions of 11.1.

**Comment by manuelgonzalezrodriguez** [comment]
Hi @dphang,

We've upgraded our Next.js version up to `11.1.2` and doing some tests (serverless version was `v3.4.0-alpha.6`) for these days and it seems problem is fixed. We haven't found any blank page with this version.

**Comment by ljosberinn** [comment]
We're still seeing this issue on v3.7, any info you'd need from our end? the resulting pages are entirely blank, not even a html tag, no error thrown so it's hard to spot aswell.

**Comment by b3nThomas** [comment]
We're also still seeing this issue intermittently using v3.7.0 & Next v11.1.4 😓

**Comment by rhoiyds** [comment]
Experiencing the exact same issue - v3.7.0 and Next 12.1.6.
@b3nThomas Did you have any advancements in this issue?

**Comment by b3nThomas** [comment]
> Experiencing the exact same issue - v3.7.0 and Next 12.1.6. @b3nThomas Did you have any advancements in this issue?

We've added a workaround in our CICD pipelines that seems to be doing the trick, haven't seen the issue re-occur since. On the regen lambda SQS queue, we set the message delay to the maximum time (900s I believe) so that no new messages come through while we're deploying. Then once we're happy it's all deployed we set the delay back to 0 to allow regenration.

We spent quite a lot of time investigating it and the issue seems to occur when regen requests come through while the everything isn't correctly synced. (Lambda versions, CloudFront, S3 etc)

Hope this helps
