### ISSUE TITLE
Rewrites to external destinations not working

### ISSUE THREAD

**Issue by danjiro** [serverless-nextjs/serverless-next.js#1858]
### Issue Summary
Rewrites to an external destination is resulting in a 404.

### Actual behavior
```
async rewrites() {
    return [
      {
        source: '/with-basePath', // automatically becomes /docs/with-basePath
        destination: '/another', // automatically becomes /docs/another
      },
      {
        // does not add /docs to /without-basePath since basePath: false is set
        // Note: this can not be used for internal rewrites e.g. `destination: '/another'`
        source: '/without-basePath',
        destination: 'https://example.com',
        basePath: false,
      },
    ];
  },
```
Internal rewrite from `/with-basePath` to `/another` works correctly. The second external destination rewrite results in a nextjs 404 error page.

### Expected behavior
Source path should be rewritten to destination path. This is working fine on a local environment.

### Versions

- @sls-next/serverless-component version: `@sls-next/serverless-component@3.5.0-alpha.3`
- Next.js version: `11.1.1`

### Checklist

- [x] You have reviewed our [DEBUGGING](https://github.com/serverless-nextjs/serverless-next.js/wiki/Debugging-Issues) wiki and have tried your best to include complete information and reproduction steps (including your configuration) as is possible.
- [x] You have reviewed the [README](https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md) and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] You have first tried using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
It's likely because of `basePath: false` and  the logic here: https://github.com/serverless-nextjs/serverless-next.js/blob/5eb89e0eb62872d16ca3bb71646592bbbc9b5405/packages/libs/core/src/route/basepath.ts#L11. I think if there is no basepath in the URL but basepath has been specified in the config, it does an early mapping to the 404 page. However there could still be redirects/rewrites that should still be matched. I believe just removing this should fix it as the default route if not matched is the 404 page: https://github.com/serverless-nextjs/serverless-next.js/blob/5eb89e0eb62872d16ca3bb71646592bbbc9b5405/packages/libs/core/src/route/page.ts#L149-L149.

Let me post a fix shortly.

**Comment by danjiro** [comment]
sdf
