### ISSUE TITLE
Question: There are some questions about this project that I can't find the answers for

### ISSUE THREAD

**Issue by zhyph** [serverless-nextjs/serverless-next.js#2390]
Hello,

I have some questions about the usage of this component in general, I'm new to it and AWS Services, I've been searching and studying, but I think if I ask it would be better since there's so little info about this.

1. Why the docs say I need to use `serverless` to deploy but when I ran it says to 
```
To run it, ensure it's installed:
npm install -g @serverless/cli

Then run:
components-v1 <command> <options>
```
Using `components-v1' works, but it's not explained why, and I can't really find an explanation anywhere.

2. Where can I find the `flags|options` of the CLI? Just like [this](https://github.com/serverless-nextjs/serverless-next.js#inputs) commands list,   e.g. `serverless --debug`.
3. When using multiple profiles in my credentials files, I can just use `components-v1 --aws-profile profile`, or should I do any extra configuration?
4. Is there any danger in pricing when deploying to AWS for tests?
5. When using `@sls-next/serverless-component`, should I declare a version here or using the lastest version should be no problem, and when declaring a version, where should I get it? From GitHub, npm, ... ? e.g. From GitHub the latest release would be 3.6.0, so `@sls-next/serverless-component@3.6.0`.

Just like I said, I've been studying for a few days, and I'm really new.
Anyway, thanks!

**Comment by craig95** [comment]
Hi @zhyph 

I'm not a maintainer but have been running into some of the same questions you have, here is what I have learned so far:

1. This project is using the Serverless components beta, not the GA version. This is because this project was started before the GA release. They say they are busy reworking it. 
Because the latest Serverless CLI uses the GA components you need to use the `components-v1` command to run any beta Serverless components. You can read more about serverless components here: https://www.serverless.com/blog/what-are-serverless-components-how-use/

2. Not sure

3. Not Sure 

4. Yes, you will incur costs when deploying to AWS for tests. You won't pay for the actual deployment but you will pay for any service your deployment uses. But since it is serverless it should be mostly just pay as you use. So if you only view your website a few times your CloudFront and Lambda usage will be very small if not nothing. You will however pay for storage on S3, but it should also not be a crazy amount. And since you are new to AWS you should also be able to make use of their generous free tier. 

5.  You don't have to declare a version, it should use the latest release version. You should only need to specify a version if you need a specific version for some reason. For example, I  am using v3.7.0-alpha.10 because it includes a fix for a problem I was experiencing.

**Comment by zhyph** [comment]
@craig95 Thanks, that helps me a lot, I'm still searching for some answers, as soon i found them i will update this post. Again, thanks.
