### ISSUE TITLE
lambda catch all route bug

### ISSUE THREAD

**Issue by johard** [serverless-nextjs/serverless-next.js#398]
{
  "errorType": "Runtime.MalformedHandlerName",
  "errorMessage": "'sls-next-build/handla/docs/[...slug].render' is not a valid handler name. Use absolute paths when specifying root directories in handler names.",
}

I get this error when deploying next.js to a lambda.

Works when developing local

next: 9.4.0
serverless-nextjs-plugin: 2.4.11

**Comment by tyler-ground** [comment]
Can you re-check the version you have installed?  The latest version of this plugin is 1.12.0-alpha.0

Do you possibly have the old retired one?

**Comment by johard** [comment]
https://www.npmjs.com/package/serverless-nextjs-plugin im runing the plugin not the https://www.npmjs.com/package/serverless-next.js

**Comment by tyler-ground** [comment]
In that case I recommend posting in https://github.com/danielcondemarin/serverless-next.js/issues as this is a different project than the one you are having issues with.

**Comment by omjokine** [comment]
I ran in to the same issue when tried to implement catch-all route: after the deployment, reloading catch-all routes caused 404. I know that serverless-components plugin is out there and it'd fix this issue, but because of the lag of stages I think it is still better to stick with this old version. Or at least I haven't figured out how to deploy numerous feature branches to same AWS account.

Anyhow. You are right, there's a problem in lambda naming. But actually there's another problem in API Gateway routes: catch-all routes are named as `{...slugs}` where as API Gateway format would be `{slugs+}`. So I fixed those two issues and plugin #worksonmymachine very nicely.

I haven't do pull request, because I'm not sure if this is the correct way to do it. It's a hacky solution, but I don't have too much understanding of this plugin or next.js so I ended up to rename handler filename and name as late as possible. So everything is done as before, but in the end of the process handler JavaScript is renamed as [dotdotdotslugs].js and also PagePath in Cloudformation is named same way. Probably NextPage.pagePath can be replaced later so String.replace() function is only ran once. But anyhow, like I said, it works on my CI/CD pipeline now.

Code diff is [available in here](https://github.com/danielcondemarin/serverless-next.js/compare/master...omjokine:feature/catch-all-routes). I also published it with gitpkg and should work if you add `"serverless-nextjs-plugin": "omjokine/serverless-next.js#serverless-nextjs-plugin-v2.5.0-alpha.1-gitpkg"` do your package.json file. But there's no guarantee that this will work in the future. I have no intention to delete it, but please fork your own version or let's make pull request out of it or something.

And one more think, it actually requires one code update, by default next router returns slug parts as an array and with this you will get them in string format. So something like `const actualSlugs = Array.isArray(router.query.slugs) ? router.query.slugs : router.query.slugs.split('/')` is required so it works as in next router.

**Comment by falsy** [comment]
@omjokine Thank you for the helpful information.

**Comment by dphang** [comment]
Closing this issue since it is for the old plugin which unfortunately is not supported anymore (though we do want to add plain Lambda support back to the component). Hopefully the workaround provided is helpful for now.

**Comment by jpranin-axia** [comment]
@dphang Just bumping my sipport for adding Lambda support to this old plugin
