### ISSUE TITLE
Feature: Create separate deployment artifacts per page lambda

### ISSUE THREAD

**Issue by danielcondemarin** [serverless-nextjs/serverless-next.js#49]
## Motivation

Currently, all the page bundles are deployed as part of a single deployment artifact. While each page lambda only require at runtime the bundle it needs, it would be more efficient to create separate artifacts.

## Proposal

Using `package: individually: true` create separate deployment artifacts per page function.
https://serverless.com/framework/docs/providers/aws/guide/packaging#packaging-functions-separately

**Comment by sja** [comment]
I would like to have sth like a marker to add fns to a blacklist where the next assets are added. Not a whitelist becaus I think most of the apps incude more pages than separate functions. If so, I would have different repos. Maybe with tags or so.

**Comment by eatarandom** [comment]
💯 

This is a must for using this plugin for a site at scale. Currently our app is 17.5mb packaged. We can reduce the bundle to ~450kb if we break them out to standalone packages for the context of each page lambda.

**Comment by fernandobandeira** [comment]
Unfortunately our app has around 120mb zipped now, this would be really helpful for us.

Related comment: https://github.com/zeit/next.js/issues/8956#issuecomment-538133285

Currently next.js isn't treeshaking the resulting functions, I've opened the issue about to solve that, we'll be able to make deployments with that but splitting the artifacts will be preferred.

That said, since we need this, we'll try to figure a solution and come up with a PR if possible for this matter =P

**Comment by danielcondemarin** [comment]
@eatarandom Might be a while before this lands, I'm currently focused on features and fixes for the new version of this project. Have you checked that out? 
The new project supports automatic statically optimised pages, which means any page you have without `getInitialProps` is compiled to HTML and uploaded to S3. This should considerably reduce your bundle size.

**Comment by fernandobandeira** [comment]
@danielcondemarin 

Do you have any tips on how we could solve this problem with the latest serverless-component plugin? 

We are willing to test things out and send an initial working PR but since we're not too familiar with the package we'd appreciate if you gave some tips or thoughts on how it'd be implemented.

 I've linked one issue with the treeshaking which should help keep the bundle smaller but we'd still prefer deploying them separately since we might hit the limit anyways.

**Comment by eatarandom** [comment]
I understand. We looked into the new project but couldn't take the risk as we near a launch date for a new product. It also looks to be a departure from the api-gateway architecture, which isn't a bad thing, but to different for us to take the risk. We might be more interested if the docs were more robust.

@fernandobandeira I modified the plugin build.js to look at the serverless.yml and key off of package:individually:true. In the loop I created separate include artifacts for each lambda. We have about 20. There is most definitely a better approach. For our case, this worked, however, our builds took forever so we had to abandon. We are continuing to investigate the right approach. We are close to reaching the default resource limit of 200.

**Comment by sheerun** [comment]
This might be solved by `split` feature that is proposed in and solves #185

**Comment by barrysteyn** [comment]
@danielcondemarin Does this apply to the new component?

**Comment by sdornan** [comment]
This does seem to apply to the new component. I'm hitting the `Request must be smaller than 69905067 bytes for the UpdateFunctionCode operation` error in my project, and none of the individual pages come anywhere close to that size.

**Comment by JonNode28** [comment]
Just ran into the size limitation for lambda code because of this: "Unzipped size must be smaller than 262144000 bytes"

**Comment by andycmaj** [comment]
also running into this with a moderately sized nextjs app.

**Comment by benjipott** [comment]
this plugin merge all bundle in one file that don't be minified , so the size of my bundle for each pages is very big and 💥  the lamda size limitation

**Comment by dphang** [comment]
I've updated FAQs on how to minimize your code, including minifying handlers and/or server-side pages code yourself via webpack config: https://github.com/serverless-nextjs/serverless-next.js/blob/master/README.md#the-lambdaedge-code-size-is-too-large. Hope this helps.

Note that internally, we also remove all JS files used only for prerendering if you do not use API routes at all, but if you do then unfortunately right now there's no Next.js official way to tell if a prerender JS file is not used for preview mode.

If someone needs it, please feel free to add a PR to add a new input to specify JS files to specifically exclude from the bundle - so that only SSR pages + preview mode pages JS.

Hopefully this is helpful to others, will close this since I think above should help.
