### ISSUE TITLE
root index with getServerSideProps always refreshes when it is linked to

### ISSUE THREAD

**Issue by danjiro** [serverless-nextjs/serverless-next.js#553]
**Describe the bug**
My `pages/index.js` is using `getServerSideProps` however whenever I navigate to '/', there is a request to `/_next/data/Vx6ssUqy_vsAbgwbMmDrO/index.json` which returns 503 lambda execution error then reloads the index page which then loads fine. Inside the manifest.json, `"/": "pages/index.js"` is under `nonDynamic` unlike other pages with getServerSideProps which are under `dynamic`. Been trying to figure this out of a few days and its driving me crazy! I'm on `@sls-next/serverless-component@1.17.0-alpha.5` and `nextjs@9.5`

Using `getStaticProps` fixes the issue but this is about using `getServerSideProps`

**Comment by danjiro** [comment]
downgrading nextjs@9.4.4 fixes this issue as mentioned in this https://github.com/serverless-nextjs/serverless-next.js/issues/539 and in the fix but they cause is different i believe

**Comment by dphang** [comment]
@danjiro I think this might have been fixed in the latest version `1.17.0-alpha.8`. Could you please try that?

I did make some routing changes for some other issues. Previously this line: https://github.com/serverless-nextjs/serverless-next.js/blob/bdd1e3f9feb7e0c9eec42de7298882dce084aa67/packages/libs/lambda-at-edge/src/default-handler.ts#L66 (URI normalization) was returning `/index` but I fixed it to return `/` as `/index` is not an actual route in the manifest, only `/` is. So Lambda would return an error

I believe Next.js has a fallback, if it can't load the data file then it does a server-side navigation i.e reloads the link, which is likely why you see the refresh behavior.

**Comment by danjiro** [comment]
awesome, thank you! any idea when it will be released?

**Comment by dphang** [comment]
Yeah it has to be manually published, I don't have permissions but I believe @danielcondemarin publishes a release every few days or so.

**Comment by danielcondemarin** [comment]
I've just published a new alpha @sls-next/serverless-component@1.17.0-alpha.9 👍
