### ISSUE TITLE
Why is serverless deploy discouraged

### ISSUE THREAD

**Issue by thesobercoder** [serverless-nextjs/serverless-next.js#560]
I was reading an [article](https://www.serverless.com/blog/ci-cd-workflow-serverless-apps-with-circleci) on how to deploy a serverless app from a CI/CD environment. The article makes use of the `sls deploy` command extensively, however since it is discouraged to be used with `serverless-next`, what other options do we have.

**Comment by danielcondemarin** [comment]
This project uses the beta version of [serverless components](https://github.com/serverless/components/tree/v1). To deploy a serverless component you simply run `serverless` instead of `serverless deploy` and that should work fine. 
In future once the project is upgraded to work with the [newer version of Serverless Components (GA)](https://www.serverless.com/blog/serverless-components-ga) then it would be `serverless deploy`.

**Comment by dphang** [comment]
@thesobercoder See the comments in this thread for CI/CD solutions: https://github.com/serverless-nextjs/serverless-next.js/issues/328#issuecomment-680187594, https://github.com/serverless-nextjs/serverless-next.js/issues/328#issuecomment-655466654.

My solution right now is to create a deployment script that syncs the `.serverless` directory with AWS S3 and deploys three different stages, all in CI/CD workflows (I use GitHub Actions, but the script I created should work for any provider).

As mentioned, with the GA version of Serverless Components you will get `serverless deploy` and I think also there would be support for syncing `serverless` state through Serverless Framework
