### ISSUE TITLE
Any advantages or disadvantages serving NextJS app with Lambda over EC2.

### ISSUE THREAD

**Issue by thevarunraja** [serverless-nextjs/serverless-next.js#561]
Thanks for the great work on this. I would like to know when to choose this approach of serving the app through Lambda@Edge over EC2. I tried to google for an answer but couldn't find any.  Thanks in advance.

**Comment by dphang** [comment]
Hey @thevarunraja,

Generally the issues are used for feature requests / bug reports, though I guess we don't have any gitter (or similar) for questions.

You can search for Lambda vs. EC2 comparisons. Lambda@Edge just means it replicates your Lambda and deploys it to all of AWS's edge locations so that code runs closer to your user. Here is one comparison: https://lumigo.io/blog/aws-lambda-vs-ec2/. I've also summarized based on my experiences:

Advantages of Lambda@Edge:

* Globally distributed, run code closer to user so there are lower network latencies and high-availability
* On-demand, i.e pay based on # requests / CPU time you use
* Don't worry about scaling your applications

Disadvantages of Lambda@Edge:

* Cold start can become an issue especially for SSR (server-side rendered) pages. This is because Lambda@Edge needs to re-initialize container (it doesn't keep it on forever) if there aren't any requests coming to it. Requiring a bunch of dependencies can be slow (in my app, it takes up to 800-1000 ms execution time on cold start).
* Not much control of the Lambda containers; you can only choose between a few Node.js runtimes, 128 - 3 GB memory (no control over CPU, although it scales with memory).
* Limits on timeout, code size, etc. (See: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html)

Advantages of EC2:

* You have complete control of OS, Node.js runtime, installed software etc and tons of hardware choices based on your needs
* No cold starts as the instances are always ready to serve traffic
* Can use Docker containers, Elastic Beanstalk to make it easier to manage your code

Disadvantages:

* You need to manage scaling your EC2 instances, which regions to deploy them to, etc. Also administering them takes time e.g updating/installing software
* Could be costlier if you don't have much traffic
* Lower availability e.g if you only have a couple of instances
* Higher network latency for those users not near your instances

Note that Next.js apps strongly prefer using statically generated (SSG) pages over SSR pages. In which case, they will mostly be served by CloudFront caches and if it hits your Lambda (cache miss), it has very light logic to figure out which page to retrieve based on URL and retrieves it from S3 instead. In my experience, it is around 20-40 ms if cached and around 100-250 ms if uncached (I do live near an edge location)

So it depends: if most of your pages can be statically generated and you need very little / no SSR pages, then Lambda@Edge is a very good choice. If you need to SSR many or all pages, then it will probably be much slower than using EC2 (network savings won't offset this).

**Comment by thevarunraja** [comment]
Thanks for your awesome explanation. This is exactly what I am looking for.  Thanks again
