### ISSUE TITLE
Root page with basePath doesn't work without trailingSlash

### ISSUE THREAD

**Issue by marcin-piela-sf** [serverless-nextjs/serverless-next.js#571]
**Describe the bug**

I see one problem after deploy, I have a basePath "test/dwa" and app returns 404 on:

https://d1g4p9lwi1bqdw.cloudfront.net/test/dwa

But it works on:
https://d1g4p9lwi1bqdw.cloudfront.net/test/dwa/

I have `trailingSlash:false` in next.js config.

```
sls-next/lambda-at-edge@1.6.0-alpha.5
```

**Expected behavior**
Root url with subPath should work with and without trailingSlash

**Comment by dphang** [comment]
Thanks, let me take a look!

**Comment by dphang** [comment]
Just tried out. I have a pages structure of the following (tested having `a/b` route to `b` page and `a/c` with index page under `c`:

```
pages
├── a
│   ├── b.tsx
│   └── c
│       └── index.tsx
└── index.tsx
```

Next config:

```js
module.exports = {
  target: 'serverless',
  trailingSlash: false
}

```

I'm deploying with `@sls-next/serverless-component@1.17.0-alpha.7`

The repro app is here: https://github.com/dphang/nextjs-repros/tree/nested-pages

The subpath `a/b` and `a/c` returns 200 and `a/b/` and `a/c/` returns a 308 redirect.

https://d113kzwzk7s27f.cloudfront.net/a/b (200)
https://d113kzwzk7s27f.cloudfront.net/a/b/ (308 redirect to a/b)
https://d113kzwzk7s27f.cloudfront.net/a/c (200)
https://d113kzwzk7s27f.cloudfront.net/a/c/ (308 redirect to a/c)

Could not reproduce any issue with this and subpaths should be covered by the tests too. Could you please share your repro code?

**Comment by marcin-piela-sf** [comment]
Sorry I wrote "subPath" but I meant "basePath" in next.config.js:
```
  basePath: '/test/dwa',
```

**Comment by dphang** [comment]
Ah, thanks for clarifying, I can reproduce the issue with `basePath`. Trying to find the bug now.

**Comment by dphang** [comment]
Found the problem. It seems to be in the normalization here:

https://github.com/serverless-nextjs/serverless-next.js/blob/ca63b80d4bf784ebfdc5a32352a53dde85b4b4d9/packages/libs/lambda-at-edge/src/default-handler.ts#L49-L58

With your base path of `/test/dwa`, URIs will remove the length of `basePath`. When you go to `/test/dwa` the URI gets stripped to `""`, and then it returned `/index` but actually `/index` is not a valid route, only `/` is. So that's why you were getting a 404.

When you go to `/test/dwa/` the URI becomes `/` and that points to index page correctly.

The fix is to update this normalization logic + handle the redirect properly from `/` to empty path

**Comment by marcin-piela-sf** [comment]
Great! Thanks!
