### ISSUE TITLE
Is it possible access to RDS another region?

### ISSUE THREAD

**Issue by XOneto9** [serverless-nextjs/serverless-next.js#610]
*****
"next": "^9.5.3",
RDS: Aurora-mysql based
*****

I know the nextjs9 has a built-in serverless module for using lambda@edge.
this is pretty wonderful, but in my case, I have used RDS another region on  ap-northeast-2

the document of lambda@edge said that the region of deploy is just `us-east-1` of Virginia.

The problem is not included in the same region VPC with lambda@edge and RDS.
How can I do to use RDS on deployed lambda@edge?
Need your help , Thanks

**Comment by dphang** [comment]
Yes, Lambda@Edge is deployed in us-east-1 (reason: it's kind of a special region for Amazon, it is their first AWS region, so I think they just use it as a central location to manage it. Also all CloudFront distributions live there as well, so it may be convenient/easier for them to integrate on their side.) but the Lambda itself is replicated to all CloudFront edge locations (~84 cities, maybe 200+ servers from what I remember).

As a result, Lambda@Edge can't access resources inside your VPC, because a VPC lives in a specific region. But it can access services and AWS resources on the public internet. So if your RDS is publicly accessible, you can connect to it using the connection string.

See here for more info: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-requirements-limits.html#lambda-requirements-network-access

Note: I would not recommend using a publicly accessible RDS instance though, due to security considerations (DDoS, brute-force attacks, etc.). Please do your own research on this, but you can consider building a small API on top of RDS (e.g using EC2 + RDS in a VPC) or at the very least whitelist only CloudFront IP addresses (I believe Lambda@Edge are deployed on the same edge servers): https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/LocationsOfEdgeServers.html

**Comment by XOneto9** [comment]
@dphang 
Thank you for rapidly answer.
As your mention, I'm clearly How RDS can connect to lambda@edge.

Also, I agree with Your opinion that a public database may have a security problem. So I think the best way is All of resources of AWS( like as RDS and other lambdas etc..) move on Virginia Region for accessing private VPC group.

Thanks I have lots of your favor

**Comment by MGough** [comment]
I've been looking into this to see if there's a nice way to ensure that we can keep our RDS instance locked down, allowing connections from Lambda@Edge only. It looks like the '[Database Proxy](https://aws.amazon.com/blogs/compute/using-amazon-rds-proxy-with-aws-lambda/)' feature of RDS might be of use.

Unfortunately I haven't had a chance to test it out as of yet, but it would be interesting to see if anyone else has already tried it. If I do have time to try it out then I'll post an update.
