### ISSUE TITLE
cloudfront cache behaviour for public assets

### ISSUE THREAD

**Issue by manojHDwork** [serverless-nextjs/serverless-next.js#612]
Thanks for all your hard work.
**Describe the bug**
Not able to cache public assets on CloudFront, if setup any cache behavior like static/* or assets/* then it failed to serve and got 403 error for the resource.
 
It only works if the cache policy public/static/* but than again failed in the local environment. 

work in local src='/static/logo.svg' , failed in cloudfront
work in cloudfront  src='/public/static/logo.svg' , failed in local

Now got in a situation where need to maintain two folders one for local and one for CloudFront. (worked)
example - path src='/public/static/logo.svg'
current folder structure

> public 
>         + static (all static files) (for cloudfront) 
>         + public / static (for local).      ( next behaviour for assets /public/static )
> 

@dphang

**Comment by pecoram** [comment]
Same issue, I had to manually set _Origin Request_ with the Lambda Function ARN in the _static/*_ behaviour settings to serve these resources

**Comment by manojHDwork** [comment]
I think with a public/static path, every time the cache miss on CloudFront which in result invoking the lambda for static assets. (not sure) @danielcondemarin

**Comment by dphang** [comment]
So to recircle back to this, if you had a directory `public/static` it's invalid because it'll conflict with the `static/*` behavior when doing routing (as mentioned this does not have Lambda origin request handler). 

So you need to move to another directory name if you want to keep it in `public`, e.g `public/another`. It will then serve correctly from `example.com/another/*` using Lambda handler, which routes it correctly to S3 under `/public/another/*`

Otherwise move it to `static` folder (at root of your app) if you want to serve it from `example.com/static/*`. This is served directly without using Lambda handler; S3 stores this under `/static/*` and CloudFront maps correctly to S3 key without using any handler.

**Comment by baj84** [comment]
Could we get some clarification on this? Should all our static images be stored in /public/images on local?

**Comment by dphang** [comment]
Yea, I believe the recommendation is to use `public` folder. I think `static` was there for legacy reasons, it doesn't have the handler so it's purely retrieving from S3.

**Comment by dphang** [comment]
Closing as I think this can be resolved, feel free to open another issue in case of any concerns.
