### ISSUE TITLE
AWS Only

### ISSUE THREAD

**Issue by Industrial** [serverless-nextjs/serverless-next.js#616]
Hi.

Can I use this only with AWS?

AWS requires you to have a credit card. GCP does not.

Also, GCP offers twice the functions invocations per month for free. (2 million, as opposed to 1 million with AWS).

**Comment by dphang** [comment]
Yeah, unfortunately it's only for AWS at the moment as the code is very coupled and optimized for Lambda handlers and AWS resources (CloudFront, S3, etc.).

Not sure what @danielcondemarin 's plans are for this, it would require a lot of refactoring. Perhaps when upgrading to Serverless Components GA, we can also think about how to abstract the AWS stuff (e.g create generic interfaces instead of referencing provider APIs directly, so we can plug-in different providers like AWS, Azure, GCP depending on the platform).

As for the AWS credit card issue, that is a limitation of AWS's business model. Unfortunately I don't have much to suggest except possibly using a debit card or prepaid card (though with prepaid cards, you should be careful of not getting charged over the limit).

**Comment by Industrial** [comment]
Okay, thanks
