### ISSUE TITLE
Passing correct Host header to _next/data/*

### ISSUE THREAD

**Issue by Qubica** [serverless-nextjs/serverless-next.js#617]
Hello,

I'm setting up a Multilang Serverless NextJS project. 
Based on the Host Header I like to retrieve the correct language via getServerSideProps. 
domain.nl -> dutch, domain.eu -> english, domain.de -> german, ... etc

This is working for the dev server, on page load and on client side routing.
On AWS it's working for page load but failing for client side routing (_next/data/*) 
When navigating on the client it's receiving the s3 domain as Host instead of the actual origin. 
In Cloudfront I've added Host to the whitelist headers.

Who can help me solve this?

**Comment by dphang** [comment]
Yes, I believe host header is explicitly set for S3 origin requests. This applies to all S3 requests including SSG data requests: https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/default-handler.ts#L308

Originally this was added in PR: https://github.com/serverless-nextjs/serverless-next.js/pull/412.

But I believe you are talking about SSR data requests since you mention getServerSideProps, so I don't think above applies. Are you also forwarding `Host` header for `_next/data` cache behavior in addition to default cache behavior? Because otherwise the `host` header is set to s3 origin host (AWS behavior).

**Comment by Qubica** [comment]
Thank you for the quick reply! 
Updating to the latest alpha release is doing the trick.
Great!
