### ISSUE TITLE
Question: How to redirect www to non-www with AWS

### ISSUE THREAD

**Issue by alan345** [serverless-nextjs/serverless-next.js#633]
With AWS, Can you guide me to redirect www to non-www to avoid duplicate content?
Should we create a s3 bucket and a new Cloud front distribution? (https://www.pbxdom.com/how-redirect-non-www-to-www-with-amazon-cloud-front-route-53-and-s3)

or, can we set it up in the `serverless.yml` file?

Thanks!

**Comment by dphang** [comment]
I think you can follow here for now: https://github.com/serverless-nextjs/serverless-next.js#i-was-expecting-for-automatic-subdomain-redirection-when-using-the-domaintype-wwwapex-input. Basically you need to manually create new S3 bucket and CloudFront distribution (for HTTPS redirect) and some new Route53 A records

In the future it's possible to support it in this component, but we would need to make a couple of changes:
* Support multiple domain inputs mapped to one distribution (so you can have www.example.com and example.com Route53 records pointing to same CF distribution)
* Lambda could return a redirect response from www.example.com -> example.com (or vice versa)

**Comment by dphang** [comment]
Now that redirects are done (https://github.com/serverless-nextjs/serverless-next.js/issues/587#issuecomment-700902584) we could leverage similar code to do a redirect from a domain name to another in the Lambda@Edge itself.

Although it's just a little bit costlier than the S3 bucket redirect (due to use of Lambda@Edge compute), it has a few advantages:

* The redirect is handled at the edge server instead of at a single point (e.g S3 bucket). This should have lower latency for most users.
* Easier to manage within this component; no need to setup two separate CF distributions and another bucket.

Caveat: currently only the default cache behavior (`/*`) have at Lambda@Edge association, so you won't be able to redirect static files under `/_next/static/*`. We could solve in the future by adding another handler for this cache behavior, but probably not worth it just for redirects.

**Comment by alan345** [comment]
thanks for your update. I have as recommended manually create new S3 bucket and CloudFront distribution and some new Route53 A record.

I have 2 CloudFront distribution :
- example.com
- www.example.com (s3 redirection)

It works well.

Now, if I deploy again via `npx serverless` I have this error:
`nextApp › CNAMEAlreadyExists: One or more of the CNAMEs you provided are already associated with a different resource.`

**Comment by dphang** [comment]
Yeah, I think you may need to set `domainType` input to `apex` only since `www.example.com` is already associated with your CF distribution for redirection. Let me know if that works.

**Comment by dphang** [comment]
I've released the PR: https://github.com/serverless-nextjs/serverless-next.js/pull/639 which can support this domain-level redirect in the Lambda@Edge itself. If you wish, you can try this method - please refer to the README for more details.

**Comment by dphang** [comment]
@pecoram it should be in 1.18.0-alpha.1. You can check the commit for the git tag for `@sls-next/serverless-component` https://github.com/serverless-nextjs/serverless-next.js/commit/a12e31ac06378f9fe26189b95a9b032942656380 (I know it's a bit confusing with the many tags, we will work on improving the release changelogs soon).
