### ISSUE TITLE
Invalid ELF header after deploying successfully

### ISSUE THREAD

**Issue by oran1248** [serverless-nextjs/serverless-next.js#661]
### Describe the bug
1. Deploying `next.js` project using `serverless-next.js` to AWS lambda. My project uses `argon2` package.
2. Deployment succeeded, but when lambda is running, getting the following error in log (CloudWatch):
![image](https://user-images.githubusercontent.com/26431778/95506892-423fa880-09b9-11eb-8e57-fbd924d43608.png)

### Actual behavior
Error in CloudWatch log

### Expected behavior
No error

### Steps to reproduce
Described above

### Versions
- Environment: AWS Lambda linux machine
- @sls-next/serverless-component@1.17.0-alpha.12

**Comment by dphang** [comment]
I'm not familiar with `argon2` but I had seen this before (not with this component, but when working with Lambda Python function). I think most likely this is due to trying to use some binary compiled for a different OS on Amazon Linux 2.

Perhaps you have to do something like this (https://aws.amazon.com/blogs/compute/nodejs-packages-in-lambda/) to build `argon2` for Amazon Linux 2 and then include this in the Lambda package when uploading. I'm not too familiar in this area but I think we would need to update the `build` step to support this?

**Comment by oran1248** [comment]
@dphang So the reason for the error is that I compiled `argon2` on Windows machine, I think I will use `docker` in order to solve this problem.

**Comment by dphang** [comment]
@oran1248 makes sense, I think if you build a Linux version via Docker, it should solve it.

**Comment by dphang** [comment]
Closing for now, do let us know if there is still an issue. Thanks!
