### ISSUE TITLE
RFC: Support getStaticPaths `fallback: 'blocking'`

### ISSUE THREAD

**Issue by strozw** [serverless-nextjs/serverless-next.js#833]
**Is your feature request related to a problem? Please describe.**

next.js 10 add support fallback blocking.
https://nextjs.org/blog/next-10#blocking-fallback-for-getstaticpaths

This feature is useful for SEO & OGP support.

**Describe the solution you'd like**

I want  html response like existing ssg fallback.

**Describe alternatives you've considered**

We are considering whether to support it with SSR.
However, from a performance standpoint, I plan to give up OGP support and use SSG fallback for the time being.

**Additional context**

I'm trying this feature in following repository.
https://github.com/strozw/sample-serverless-nextjs

**Comment by arelaxend** [comment]
@strozw totally agree. I found more details under https://dev.to/tomdohnal/blocking-fallback-for-getstaticpaths-new-next-js-10-feature-1727

**Comment by arelaxend** [comment]
any update ?

**Comment by arelaxend** [comment]
any updates about the next release ?

**Comment by dphang** [comment]
@arelaxend sorry I haven't had as much time this month but if you want to work on it, I'd be happy to review the PR. If not I can probably work on it once I have more time (maybe end of month or next month). Though fallback logic is a bit interesting since we are using origin request + origin response handler (actually we were thinking of trying to simplify to one handler).

For blocking fallback, I think we should check if `fallback:blocking` is enabled in origin request handler and render + save the response in S3, then return it.

**Comment by sinuheshinbr** [comment]
The implementation of this feature would be much appreciated!

**Comment by thaiphan** [comment]
Thanks for this library! This feature would be something that I would love to use!

**Comment by evangow** [comment]
@dphang  I wrote some pseudocode to address { fallback: "blocking } along with setting a revalidation parameter in the issue here https://github.com/serverless-nextjs/serverless-next.js/issues/804#issuecomment-782565190
