### ISSUE TITLE
Cannot pass params to sls

### ISSUE THREAD

**Issue by Bielik20** [serverless-nextjs/serverless-next.js#856]
### Describe the bug
When I try to pass parameter:
```
sls --distDir ../../dist/apps/desktop
```
I cannot use `distDir` in `serverless.yml`. I get an error (in Screenshots/Code/Logs section)
When I hard code value inside `serverless.yml` it works fine.

### Actual behavior
I cannot use passed parameters.

### Expected behavior
I should be able to use passed parameters.

### Steps to reproduce
Run:
```
sls --distDir ../../dist/apps/desktop
```
Try to use `distDir` somewhere in `serverless.yml`

#### serverless.yml
```yml
# serverless.yml
distDir: ''

my-app:
  component: "@sls-next/serverless-component@1.18"
  inputs:
    nextConfigDir: ${distDir}
    build:
      cmd: "nx"
      args: ["run", "desktop:build:production"]
      cwd: "../../"
```

#### Error:
```
  Error: invalid reference ${distDir}
    at Object.<anonymous> (/Users/damianbielecki/Projects/_private/argus/node_modules/@serverless/template/utils.js:128:19)
    at walker (/Users/damianbielecki/Projects/_private/argus/node_modules/traverse/index.js:190:22)
    at /Users/damianbielecki/Projects/_private/argus/node_modules/traverse/index.js:208:29
    at Array.forEach (<anonymous>)
    at forEach (/Users/damianbielecki/Projects/_private/argus/node_modules/traverse/index.js:298:31)
    at walker (/Users/damianbielecki/Projects/_private/argus/node_modules/traverse/index.js:203:13)
    at /Users/damianbielecki/Projects/_private/argus/node_modules/traverse/index.js:208:29
    at Array.forEach (<anonymous>)
    at forEach (/Users/damianbielecki/Projects/_private/argus/node_modules/traverse/index.js:298:31)
    at walker (/Users/damianbielecki/Projects/_private/argus/node_modules/traverse/index.js:203:13)
```
### Versions

- OS/Environment: MacOs 10.15.7
- @sls-next/serverless-component version: 1.18
- Next.js version: 10.0.1

### Additional context
I have stumbled upon this issue https://github.com/serverless-nextjs/serverless-next.js/issues/808 but it didn't help. Perhaps I am passing parameters in a wrong way. In that case it would be good to update [documentation](https://github.com/serverless-nextjs/serverless-next.js#i-require-passing-additional-information-into-my-build)

### Checklist
- [x] You have reviewed the README and [FAQs](https://github.com/serverless-nextjs/serverless-next.js#faq), which answers several common questions.
- [x] Please first try using the most recent `latest` or `alpha` `@sls-next/serverless-component` [release version](https://github.com/serverless-nextjs/serverless-next.js/releases), which may have already fixed your issue or implemented the feature you are trying to use. Note that the old `serverless-next.js` component and the `serverless-next.js` plugin are deprecated and no longer maintained.

**Comment by dphang** [comment]
Not sure if Serverless Components supports that (I think it is in vanilla Serverless Framework). Or if the latest Serverless Components does, it might be that we are still on the Components beta unfortunately due to lack of resources =( 

One workaround could be to use environment variables instead. Similar workarond for a different problem here: https://github.com/serverless-nextjs/serverless-next.js#concatenating-environment-variables-doesnt-seem-to-work

**Comment by Bielik20** [comment]
Thank you for response. I guess passing params as env variables is an acceptable workaround 🙇 

As far as serverless components are concerned, I think they support it as described in here: https://github.com/serverless/components#variables

**Comment by dphang** [comment]
Thanks @Bielik20. I did see that, though that readme is for the GA version, we are still on beta unfortunately (https://github.com/serverless/components/tree/v1) so probably it wasn't implemented by Serverless team yet in that version.

I will resolve for now since there is a workaround, we do have some other tracking issues for upgrading to the GA version, though we haven't had resources/interest yet to work on it. Though in interest of transparency, Serverless Framework will give some funding to upgrade, which we have not claimed yet. Probably I will discuss internally how we can move it forward, perhaps creating an issue. Perhaps the financial incentive would be enough for someone to take it up (I would do it myself, but I had less time in the last couple of months).
