### ISSUE TITLE
Rewrites not working

### ISSUE THREAD

**Issue by BoazKG93** [serverless-nextjs/serverless-next.js#870]
I have an iframe with the following url in my code:
`<iframe src="/mp-sdk/somestuff"></iframe>`

I'm trying to use the nextjs rewrite in my next.config.js as follows:
```

const withSass = require("@zeit/next-sass");
const withCSS = require("@zeit/next-css");
const withImages = require("next-images");

const path = require("path");

module.exports = withImages(
  withCSS(
    withSass({
      target: "serverless",
      sassOptions: {
        includePaths: [path.join(__dirname, "styles")],
      },
      async rewrites() {
        return [
          {
            source: "/mp-sdk/:path*",
            destination: `https://example.com/mp-sdk/:path*`,
          },
        ];
      }
    })
  )
);
```

It works perfectly fine on localhost, but when I deploy to Lambda@Edge, it doesn't work anymore. Is there any way around this? I tried to write a lambda function that does the rewrite, but it has to be on origin request, which is already used by serverless. I'm using @sls-next/serverless-component@1.18.0

**Comment by dphang** [comment]
How are you calling `/mp-sdk/:path*`, and what do the CloudWatch logs say? 

Note I did fix an issue where headers, body and method were not being passed for external rewrites: https://github.com/serverless-nextjs/serverless-next.js/issues/863. It is in the latest alpha version, so it may fix your problem.

**Comment by BoazKG93** [comment]
I'm calling it in an iframe, written in my HTML in one of the dynamic components.
as follows:
```
<iframe src="/mp-sdk/3.1.16/showcase.html?m=test />
```

So very very simple.

I'' try moving to 1.19.0-alpha.26 and will update shortly

**Comment by BoazKG93** [comment]
Ok after upgrading to 1.19.0-alpha.26 I get now `503`.

You can check the log here:
https://test.treedis.com/tour/house

**Comment by dphang** [comment]
Ah I see, so it should just make a GET request. Yes, it passes all query parameters as well.

I loaded that page but just getting the generic 503 Lambda error page (see: https://test.treedis.com/mp-sdk/3.1.16/js/showcase.js). You will need to look into CloudWatch logs in the region closest to where you are accessing the app as it's hard to debug otherwise what's happening.

**Comment by BoazKG93** [comment]
I'm getting:
{
  "errorMessage": "Response payload size (7882208 bytes) exceeded maximum allowed payload size (6291556 bytes).",
  "errorType": "Function.ResponseSizeTooLarge"
}


It should do rewrite from
https://test.treedis.com/mp-sdk/3.1.16/js/showcase.js
to 
https://static.treedis.com/mp-sdk/3.1.16/js/showcase.js

Without a rewrite, hence if I host /mp-sdk/ on the public folder of my nextjs project, it works fine.

**Comment by dphang** [comment]
Yes, I think this is a Lambda limitation: https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html, also it doesn't seem like that file is being compressed either, and the rewrite function in this component doesn't compress content; it is just a passthrough (apart from removing restricted/read-only CloudFront headers from the response). If you compress it, it may be possible to do it through the Lambda.

**Comment by BoazKG93** [comment]
Yes, this is what strange about it.
Try now: https://test.treedis.com/mp-sdk/3.1.16/js/showcase.js
This is without a rewrite.

So without a rewrite it returns it through HTTP without any issues, with the rewrite it complains about the size. I'm wondering why.

**Comment by dphang** [comment]
I believe that's because it is being served from S3, not Lambda@Edge, so it does not have the size limitation.

**Comment by dphang** [comment]
As mentioned, I have updated the external rewrite to be more performant; it doesn't do any decompression at all in the `fetch` call (which would fail the Lambda@Edge response size limit whether you have compression enabled/disable at the origin) as proxies the response as is. It's published in the latest alpha version.

So if you are able to compress your JS content at the origin i.e https://static.treedis.com/mp-sdk/3.1.16/js/showcase.js (which looks like CloudFront, so you should be able to since it is JS content type) to be less than the limit, then it should now work through the Lambda@Edge external rewrite.

Otherwise, you will need to serve it from S3. I'm closing this issue now since I believe there is nothing else needed to be done on our side.
