### ISSUE TITLE
TypeError: uploadAssetsToS3.default is not a function

### ISSUE THREAD

**Issue by utiq** [serverless-nextjs/serverless-next.js#874]
```
  DEBUG ─ Deploying bucket nbd4dq8-hfq07z in region us-east-1.
  DEBUG ─ Checking if bucket nbd4dq8-hfq07z exists.
  DEBUG ─ Setting acceleration to "true" for bucket nbd4dq8-hfq07z.
  DEBUG ─ Bucket nbd4dq8-hfq07z was successfully deployed to the us-east-1 region.

  error:
  TypeError: uploadAssetsToS3.default is not a function
    at NextjsComponent.deploy (/home/.serverless/components/registry/npm/serverless-next.js@1.15.0-alpha.2/node_modules/serverless-next.js/serverless.js:187:35)
    at async fn (/mnt/c/Users/code/myApp/node_modules/@serverless/template/utils.js:280:41)
    at async Promise.all (index 0)
    at async executeGraph (/mnt/c/Users/code/myApp/node_modules/@serverless/template/utils.js:294:3)
    at async Template.default (/mnt/c/Users/code/myApp/node_modules/@serverless/template/serverless.js:67:38)
    at async Object.runComponents (/mnt/c/Users/code/myApp/node_modules/@serverless/cli/src/index.js:220:17)

  103s › myApp › TypeError: uploadAssetsToS3.default is not a function
```

serverless-next.js in package.json
`"serverless-next.js":"^1.15.0-alpha.2"`

my serverless.yml
```
myApp:
 component: serverless-next.js
 inputs:
  domain: ["mydomain.com"]
```

serverless --version
```
Framework Core: 2.18.0
Plugin: 4.4.2
SDK: 2.3.2
Components: 3.4.7
```

**Comment by dphang** [comment]
It might be due to the version pinning issue which happened in versions below 1.17 if I recall correctly, causing the component to use internal dependency versions from future versions (because it was not pinned). It is recommended to update to 1.18 or 1.19 alpha if possible which has fixed this. Otherwise, there is also one-time 1.15 patch version that pinned internal dependencies here: https://www.npmjs.com/package/@sls-next/serverless-component/v/1.15.0-patch.0

**Comment by utiq** [comment]
I updated my package.json but still getting the same error, my package.json content:
```
myApp:
 component: "@sls-next/serverless-component@1.18.0"
 inputs:
  domain: ["mydomain.com"]
```

**Comment by dphang** [comment]
Hm, the reason is that `uploadAssetsToS3` function was removed from internal package `@sls-next/s3-static-assets` in this commit: https://github.com/serverless-nextjs/serverless-next.js/commit/000377d2dbc5c7fab53b11ff7f36b0367d706b49. Due to not pinning internal dependencies properly, 1.15 will try to call this function from the main component package, but it's using a newer dependency version where this was already removed.

I did check for 1.18 and it is no longer using `uploadAssetsToS3` function at all from the main component and it's also been removed in internal dependency `@sls-next/s3-static-assets`, so not quite sure why you still have same issue.

Could you maybe remove all modules in your Serverless registry in case it might be using some old code? I think on Mac it should be in`/Users/<user>/.serverless/components/registry` (sorry, not sure where it would be in other OSes)

**Comment by utiq** [comment]
Thanks! changing to "@sls-next/serverless-component@1.18" and removing previous data made it work.

**Comment by dphang** [comment]
I see, glad it works now. Resolving this issue.
