### ISSUE TITLE
FYI: My chat w/ sls support Re: Deployment to a live domain

### ISSUE THREAD

**Issue by msimonc** [serverless-nextjs/serverless-next.js#890]
Q: trying to deploy my sls-next component app to my aws purchased domain abc123.us 

app: abc123
#component: website   # what goes here?
name: abc123-fe
org: abc123org
abc123-fe:
  component: "@sls-next/serverless-component@1.18.0"
inputs:
  name: ${name}
  domain: abc123.us
  region: ap-southeast-2

When running "sls deploy" I used to be able to uncomment the "component" line but now get Error: "component" input is required to run custom methods.  the Next JS component deploys to cloudfront when I run "sls".

A: Unfortunately the Next JS component is currently out of date and does not deploy correctly using the new components backend. I have heard the author is working on correcting it and we have worked with them to try and get it up to date but at this point we need to wait for them to finish their work.

**Comment by otekdo** [comment]
Hi @msimonc, as i understand you wanna know how to deploy your nextjs app to aws. with your live domain.
Before everything these are the important requirements:

**1-You must have your domain registered in Amazon AWS Route 53**

**2-You must authenticate an IAM user of your AWS account with serverless** 
**Quick tip:** If you do not want to be specific with permissions policies of your account
You can just assign the following policy:  **AdministratorAccess**
For more details go here:
https://www.serverless.com/framework/docs/providers/aws/cli-reference/config-credentials/

Now, **try to follow this example** in order to understand better what you want to do

serverless.yml (Name of file)

```
abcWebsite:
  component: "@sls-next/serverless-component@1.18.0"
  inputs:
    domain: "abc123.us"
    description: Description of my website
    memory:
      defaultLambda: 1024
```

Well, as you can see from that example:

**1- You do not need to set region because your app is deployed in an CDN "AWS CLOUDFRONT"**
**2- abcWebsite means that's the name of your app, but from my personal experience, i recommend you to use description**
_The description is useful, because you can identify you lambda functions easily in the AWS console_

**3- In the component, you must specify the version of that component**
       _At the time this comment is published, that is the recent stable release:_

![image](https://user-images.githubusercontent.com/65221868/106345997-891c1b80-6292-11eb-881c-7bb775cb09eb.png)


4-As you can see in the example, **you must format the yml properly**
5-In the input section, you can see how you will asign your domain, description, and also memory of the lambda function

If you want, **try to download this serverless.yml** file and replace the one that you have:

[compressed.zip](https://github.com/serverless-nextjs/serverless-next.js/files/5897300/compressed.zip)

**Comment by msimonc** [comment]
Works, thanks!  I will inform sls support.
