### ISSUE TITLE
Integrate external services to API routes

### ISSUE THREAD

**Issue by jgoux** [serverless-nextjs/serverless-next.js#891]
Hello 👋 ,

**Is your feature request related to a problem? Please describe.**
In the README : 
> API Routes. Similarly to the server side rendered pages, API requests are also served from the CloudFront edge locations using Lambda@Edge.

Does it mean that we can't call a Aurora PostgreSQL database from our API routes when deployed on AWS? As it's required to be in the same VPC. Is there any option to scope the API routes to a single region/VPC?

**Describe the solution you'd like**
Ideally I'd like to use this component to deploy my Next.js application on AWS. And my API routes need other services from AWS (Aurora PostgreSQL, SNS, SQS, S3).

**Describe alternatives you've considered**
I don't have any solution right now.

Thanks for your help. 😄

**Comment by dphang** [comment]
Yes you can, though AWS Lambda@Edge runs on the edge among globally distributed nodes, so that is why it cannot be in VPC (unlike a normal Lambda). Also furthermore, they do not support environment variables. So if you want to connect to a SQL database then you may need to have the credentials in-lined in your Lambda@Edge function code.

I know there are ways like using AWS Secrets Manager (e.g https://aws.amazon.com/blogs/networking-and-content-delivery/securing-and-accessing-secrets-from-lambdaedge-using-aws-secrets-manager/) to be more secure for secrets. Maybe it also support IAM authentications to internal AWS services/DBs?
