### ISSUE TITLE
Connect to RDS Database Using RDS Proxy

### ISSUE THREAD

**Issue by tonestrike** [serverless-nextjs/serverless-next.js#893]
**Is your feature request related to a problem? Please describe.**
I am trying to connect to an RDS Database using RDS Proxy. Because the Lambda must be inside a VPN and this deploys the Lambda via Lambda@Edge, I am unable to deploy when connected to the RDS Proxy.

**Describe the solution you'd like**
Have the option to toggle whether to use Lambda@Edge

**Comment by dphang** [comment]
Yes, unfortunately this is due to using Lambda@Edge which cannot be in VPC. We are slowly trying to genericize the component more so it's not tied to Lambda@Edge, and then once that is done we can add other provider support (Lambda, GCP, etc.). Once I can finish the majority of Next.js 10 features then we will work on it. We will track in the other existing larger GH issues.
