### ISSUE TITLE
Mute log Deploying progress optionally

### ISSUE THREAD

**Issue by ungarida** [serverless-nextjs/serverless-next.js#904]
**Is your feature request related to a problem? Please describe.**
In the GitHub Actions the "Deploying ..." log message is making a lot of noise printing many lines like:
```
0s › Template › Deploying .
```
It looks good on normal terminal but I guess there are many other situation where this "animation" is not useful at all.

**Describe the solution you'd like**
Would be enough to have a command line parameter to mute the progress messages

**Comment by dphang** [comment]
Unfortunately, I think this was an issue with serverless component CLI (see: https://github.com/serverless-nextjs/serverless-next.js/issues/706). It might be fixed in latest GA version (not sure), though we are still using beta version since we need to upgrade (lack of resources right now, it is a major upgrade). Please keep an eye on that issue for now.
