### ISSUE TITLE
Is possible exclude some assets that I have been uploaded in /static/? 

### ISSUE THREAD

**Issue by carllx** [serverless-nextjs/serverless-next.js#905]
There are some assets(about 4GB) in the path `'/static/*'`, I don’t want to upload every time. I would like to ask if `serverless.yml`  allows me to filter those large files that I have been uploaded, won't make me wait for 40 minutes to see the result.

**Comment by dphang** [comment]
Right now there isn't a built-in way, but I think you can do a similar thing using the `postBuildCommands`, which allows you to run any command/script in between build and deploy steps. I think you can write a script to remove files you don't want to re-upload from the `static` directory

**Comment by carllx** [comment]
@dphang Thank you for providing the `postBuildCommands`, indeed,Now I Manually drag and drop static to other places when uploading, and then drag it back during development. 
Therefore, I need `postBuildCommands`, and I also need a hook when I finished upload,  execute  commands to move files back. Hope there is an option to ignore the files, which is more friendly way .

**Comment by dphang** [comment]
Yeah, basically for that command I was thinking you can just always remove the assets you don't want to upload in `.serverless_nextjs` folder. The deploy process only looks at that folder only to upload assets.

If you have written a script, feel free to adapt it back into the code via a PR so others can benefit:). Also in the future we will hopefully start to use more configurable deployment ways such as using CDK (there is experimental template already written in the repo) which you can adapt.

I'll resolve this since the workaround should work for now.

**Comment by carllx** [comment]
Thank you @dphang , after trying, I realized that postBuildCommands is a very helpful command.

@1.18.0 does not support, the use of `postBuildCommands` needs to be upgraded to "@sls-next/serverless-component@1.19.0-alpha.35"

Like @dphang said, in order to save unnecessary time, we can delete files that do not need to be uploaded repeatedly before uploading.

serverless.yml
```
myApp:
  component: "@sls-next/serverless-component@1.19.0-alpha.35"
  inputs:
    build: 
      postBuildCommands: ["node rmpath-prepost.js"]
```

rmpath-prepost.js
```node
// const fs = require("fs");
const rimraf = require("rimraf");

console.debug("**Copying locales directory...");

const removePath = "./.serverless_nextjs/assets/static/nd";
try {
  //  fs.unlinkSync(removePath); //cause errors npm Error: EPERM: operation not permitted, unlink
  rimraf.sync(removePath);
} catch (err) {
  console.error(err);
}

console.debug("**Locale directory was copied successfully**");
```
