### ISSUE TITLE
Aliases doesn't work

### ISSUE THREAD

**Issue by L-Luciano** [serverless-nextjs/serverless-next.js#911]
### Describe the bug
My yaml : 

` 
domain: ['prod', 'neo.tv'] # [ sub-domain, domain ]
aliases: ["www1.neo.tv", "prod.neo.tv"]
`

### Actual behavior
My cloudfront distribution has only "prod.neo.tv" cnames.

### Expected behavior
both "www1.neo.tv", "prod.neo.tv" in cnames

### Versions

- OS/Environment: MAC
- @sls-next/serverless-component version: '@sls-next/serverless-component@1.19.0-alpha.33'
- Next.js version: 10.0.5

**Comment by dphang** [comment]
I believe this is because domain and aliases kind of conflict (because domain input has some magic behind the scenes where it does stuff with Route53, certs + CloudFront aliases). So I think the aliases are being overridden by code behind the domain input.

I would recommend to manage domain/cert outside this component, and then you can uses aliases... not sure we will invest in refactoring this given the other efforts to use CDK instead

**Comment by dphang** [comment]
Closing out past issues - please open new one if there are further questions.
