### ISSUE TITLE
feat(AWS Lambda): Add support for `nodejs14.x` runtime #8894

### ISSUE THREAD

**Issue by t829702** [serverless-nextjs/serverless-next.js#915]
I'm trying to deploy a next app with serverless.yml:

```yaml
nextXxxxxx:
  component: "@sls-next/serverless-component@1.18.0"
  inputs:
    runtime:
      apiLambda: "nodejs14.x"
```

it failed with:

```
  error:
  InvalidLambdaFunctionAssociation: The function has a runtime that is not supported by
  Lambda@Edge: nodejs14.x Function: arn:aws:lambda:us-east-1:xxxxxxxxxxxxxx:42
Supported runtimes: [nodejs12.x, nodejs8.10, nodejs10.x, nodejs6.10, python3.7, python3.8]
```

I believe this npm package `@sls-next/serverless-component` need some change similar to serverless/serverless#8894

**Comment by dphang** [comment]
Actually we don't hardcode any specific Lambda runtime that user must choose - so that message is coming from AWS telling you which runtimes are supported.

Yes, Lambda supports Node 14 now (https://aws.amazon.com/about-aws/whats-new/2021/02/aws-lambda-now-supports-node-js-14/) but Lambda@Edge is slightly different/more limited since it's running at the edge CloudFront locations, it looks like only Node 12.x is supported so far.

I think Node 14.x should come to Lambda@Edge pretty soon, hopefully within a couple months?

**Comment by paleite** [comment]
Should be supported now:
![image](https://user-images.githubusercontent.com/4430528/113310266-5630eb00-9308-11eb-8a4c-8a01c0545f9a.png)
