### ISSUE TITLE
AWS China deployments fail - enable/disable accelerated s3 bucket

### ISSUE THREAD

**Issue by CodysseusX** [serverless-nextjs/serverless-next.js#919]
This is a follow-up to https://github.com/serverless-nextjs/serverless-next.js/pull/443.

Having the same problem when deploying to **China**. I understand that you are doing a check if the bucket acceleration is available or not before uploading: https://github.com/danielcondemarin/serverless-next.js/blob/1f47c3ebd0893336ddf55f4b909e9c232a50310f/packages/s3-static-assets/src/lib/s3.ts#L35

Unfortunately, when I call the get-bucket-accelerate-configuration using the AWS CLI, I am getting the same error: An error occurred (UnsupportedArgument) when calling the GetBucketAccelerateConfiguration operation: The request contained an unsupported argument. This means that in China the feature is disabled and what I get back is an UnsupportedArgument Exception of some kind.

In other regions, the AWS CLI API calls have no issues. I am able to get and put the accelerate configuration of the bucket with no issues. So, at the moment deployments to China using the serverless-next.js component seem to be impossible.

Unless, there is a workaround that I am not aware of. Thank you.

**Comment by CodysseusX** [comment]
"Amazon S3 Transfer Acceleration is not supported in the Beijing and Ningxia Regions."
https://docs.amazonaws.cn/en_us/aws/latest/userguide/s3.html

**Comment by CodysseusX** [comment]
So, when I run this with sls --debug, this is the output:
 DEBUG ─ Deploying bucket _bucketName_ in region cn-north-1.
  DEBUG ─ Checking if bucket _bucketName_  exists.
  DEBUG ─ Setting acceleration to "true" for bucket _bucketName_ .

Then, it fails with message: 'The request contained an unsupported argument.',  code: 'UnsupportedArgument'.

**Comment by dphang** [comment]
Yes I think it probably makes sense to just have an input to make it easy to enable/disable, seems that referenced PR was just closed without a simple solution.

I believe that error should be coming from `@serverless/aws-s3` (from serverless framework) since accelerated is always passed as true: https://github.com/serverless-nextjs/serverless-next.js/blob/673f32f90b1323018b0c833b235547fa2bf3479b/packages/serverless-components/nextjs-component/src/component.ts#L316-L316.
