### ISSUE TITLE
Generating PDF from React Component (rendered HTML)

### ISSUE THREAD

**Issue by ashvinmittal** [serverless-nextjs/serverless-next.js#925]
**Is your feature request related to a problem? Please describe.**
I am trying to use "puppeteer-core" and "chrome-aws-lambda" libraries to create pdf from html that is rendered on the server side from a react component, but it fails with this error - 
`"ERROR	Unhandled error during request: [Error: ENOENT: no such file or directory, open '/bin/chromium.br'] {  errno: -2,  syscall: 'open',  path: '/bin/chromium.br'}"`
Subsequent attempts give below error - 
`Error: spawn ETXTBSY    at ChildProcess.spawn (internal/child_process.js:408:11)    at Object.spawn (child_process.js:553:9)    at BrowserRunner.start...`

**Describe the solution you'd like**
Successful creation and rendering of PDF file from a react component.

**Describe alternatives you've considered**
Use a separate non serverless-next application using normal serverless framework. Also this works fine in a normal nextjs application.

**Additional context**
Sample Code
```
import {renderToStaticMarkup} from 'react-dom/server';
import chromium from 'chrome-aws-lambda';

const componentToPDFBuffer = async component => {
    const html = renderToStaticMarkup(component);
    console.log('going to launch puppeteer 5678');
    console.log('html is ', html);
    console.log('lambda execution path', process.env.LAMBDA_RUNTIME_DIR);
    const path = await chromium.executablePath;
    console.log('chrome path ', path);
    

    const browser = await chromium.puppeteer.launch({
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath: path,
        headless: chromium.headless,
        ignoreHTTPSErrors: true,
    });
    const page = await browser.newPage();

    await page.setContent(html, {waitUntil: 'networkidle0', timeout: 30000});
    const pdf = await page.pdf({
        format: 'A4',
        printBackground: true
    });
    await browser.close();
    return pdf;

};
export default {
    componentToPDFBuffer
};
```

**Comment by dphang** [comment]
I am not familiar with that but I think Lambda@Edge does not have Chromium installed? It would need a copy of the Chromium binary to be uploaded in the code. In a normal Lambda, I believe you can use Lambda layers to do so.

But I think here you can `postBuildCommands` to add a script to copy the binary to the default/API Lambda (whichever you need). It should be under `/var/task`. Then see if you can configure your `chrome-aws-lambda` to use the right Chromium.

**Comment by ashvinmittal** [comment]
Yes that is the issue looks like (the binaries are not copied), shouldn't serverless-next do it automatically?

**Comment by dphang** [comment]
Yes I think there are many packages that may need binaries, but serverless-next.js doesn't know how to copy it. Maybe we can add for some common binaries but it will be hard to maintain. If there is some generic way to figure out what binaries are needed, that will be better, but otherwise the next best way is to give ability to copy additional required dependencies into the Lambda (that's the `postBuildCommands` function).

**Comment by ashvinmittal** [comment]
Dependency is declared in `package.json` below is code snippet.
`{
  "name": "learn-starter",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "@sls-next/serverless-component": "^1.18.0",
    "chrome-aws-lambda": "^7.0.0",
    "next": "^10.0.0",
    "puppeteer-core": "^8.0.0",
    "react": "17.0.1",
    "react-dom": "17.0.1"
  }
}
`
is there any example of using `postBuildCommands` function ? Thank you so much for looking into this.

**Comment by dphang** [comment]
There is just simple example here https://github.com/serverless-nextjs/serverless-next.js/blob/1f64f3678b9142baf3876022c925852969dbc96a/packages/e2e-tests/next-app/serverless.yml but basically you can run any command to execute a script. Basically you might want to use packages like `fs-extra` to copy the right binaries as needed into your Lambda if your code requires them.

I will close it, hopefully it is helpful to use this config, otherwise it might be hard to support every third party package
