### ISSUE TITLE
Incorrect routing precedence for SSR

### ISSUE THREAD

**Issue by darren-charterindex** [serverless-nextjs/serverless-next.js#967]
hello, I am seeing catch-all routes taking priority over dynamic routes on the SSR.

For example:

A request for `/products/123`

_CSR (correct)_
```
/pages/example
/pages/products/[id] <- renders
/pages/[...slugs] 
```

_**SSR (incorrect)**_
```
/pages/example
/pages/products/[id]
/pages/[...slugs] <- renders
```

A request for `/parent/child`

_CSR (correct)_
```
/pages/example
/pages/products/[id]
/pages/[...slugs] <- renders
```

_SSR (correct)_
```
/pages/example
/pages/products/[id]
/pages/[...slugs] <- renders
```

A request for `/example`

_CSR (correct)_
```
/pages/example <- renders
/pages/products/[id]
/pages/[...slugs]
```

_SSR (correct)_
```
/pages/example <- renders
/pages/products/[id]
/pages/[...slugs]
```

It is my understanding that the precedence for routes should be _predefined > dynamic > catch-all > optional-catch-all_

https://nextjs.org/docs/routing/dynamic-routes#caveats

This is happening on Next.js@10.0.9 and serverless-next.js@@1.19.0-alpha.39.

**Comment by dphang** [comment]
I think this should fix it: https://github.com/serverless-nextjs/serverless-next.js/pull/974. I think the cause is all dynamic routes are grouped together (including catch all), so if catch all is resolved first before other dynamic routes, the precedence may be wrong. It is tested in e2e tests but somehow (maybe due to naming of routes causing wrong order?), the catch all always came after, so it happened to work. The fix will separate them so at runtime, we can try to match dynamic routes before catch all routes.

**Comment by mdsavian** [comment]
It still doesn't work for me. When I do a build, these files are generated, but are not copied to serverles

![image](https://user-images.githubusercontent.com/19864469/113317413-ba8e8300-92e5-11eb-96a7-a839d1367ef7.png)

**Comment by dphang** [comment]
@mdsavian sorry I am not sure which issue you are talking about, seems not related to catch all route precedence? Could you please open an issue with more context include versions, serverless.yml file and what you are trying to do. Thanks!

@darren-charterindex this is published in latest version, please comment in case of any issues

**Comment by mdsavian** [comment]
I fall into a new issue with ISG revalidation, so I wait until #804 is resolved, thanks :D
