### ISSUE TITLE
What's happening inside the the index.js file within the Lambda

### ISSUE THREAD

**Issue by MangoChris** [serverless-nextjs/serverless-next.js#978]
Firstly thanks so much for providing this project it looks awesome!

I'm just evaluating it to see if it might be suitable for a project of mine and have setup a sample project and got everything working, the setup was extremely easy.

One small concern I have though is in regards to what is happening within index.js of the lambda package. I thought I would have a quick look to see how it works and then saw it contained 15,000 lines.

As it's TLTR I was wondering if anyone could help me out and give me the short answer of what's in there and what it's doing?

Thanks again!

**Comment by dphang** [comment]
Hey @MangoChris, the file is the main handler for all the pages / API routes, basically figuring out what file/page the client is requesting and routing to the correct file (e.g in S3, or rendering a JS page if it's SSR), handling redirects, rewrites, etc.

It is 15k+ lines long since it uses Rollup to compile and bundle down to a single file including all dependencies. The reason for this is to optimize for Lambda since having multiple files causes high load times. You can see the actual code here, hopefully it is easier to understand: https://github.com/serverless-nextjs/serverless-next.js/blob/master/packages/libs/lambda-at-edge/src/default-handler.ts

**Comment by MangoChris** [comment]
Great, that is indeed much easier to understand! Thanks for your help.
